import {
  SiJavascript as Javascript,
  // SiSass as Sass,
  SiJest as Jest,
  SiPrisma as Prisma,
  SiMongodb as MongoDB,
  SiReact as React,
  SiNextdotjs as Next,
  SiTypescript as Typescript,
  SiNodedotjs as Node,
  SiPostgresql as PostgreSQL,
  SiDocker as Docker,
  SiGit as Git,
  SiChakraui as ChakraUi,
  SiNestjs as NestJs,
  SiSpring as Spring,
} from "react-icons/si";
import { FaAws as AWS, FaJava as Java } from "react-icons/fa";

export const icons = [
  Javascript,
  Node,
  React,
  PostgreSQL,
  MongoDB,
  Typescript,
  Docker,
  Next,
  Git,
  Prisma,
  Jest,
  ChakraUi,
  NestJs,
  AWS,
  Java,
  Spring,
];

export const iconNames = [
  "Javascript",
  "Node",
  "React",
  "PostgreSQL",
  "MongoDB",
  "Typescript",
  "Docker",
  "Next",
  "Git",
  "Prisma",
  "Jest",
  "ChakraUi",
  "NestJs",
  "AWS",
  "Java",
  "Spring",
];
